"""swipe session recipe match

Revision ID: 00b898f6b7ea
Revises: 0538d40cef43
Create Date: 2023-06-12 14:58:30.105089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b898f6b7ea'
down_revision = '0538d40cef43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('session_match', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'swipe_session', 'recipe', ['session_match'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swipe_session', type_='foreignkey')
    op.drop_column('swipe_session', 'session_match')
    # ### end Alembic commands ###
