"""correct swipe_session_queue FK

Revision ID: 0538d40cef43
Revises: 855d38236fd8
Create Date: 2023-06-12 11:52:31.548782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0538d40cef43'
down_revision = '855d38236fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_recipe_queue_swipe_session_id_fkey', 'session_recipe_queue', type_='foreignkey')
    op.create_foreign_key(None, 'session_recipe_queue', 'swipe_session', ['swipe_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_recipe_queue', type_='foreignkey')
    op.create_foreign_key('session_recipe_queue_swipe_session_id_fkey', 'session_recipe_queue', 'user', ['swipe_session_id'], ['id'])
    # ### end Alembic commands ###
