"""add SwipeSesionRecipeQueue

Revision ID: 1318b666e8ea
Revises: e4d09e5f8715
Create Date: 2023-06-06 11:35:56.595766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1318b666e8ea'
down_revision = 'e4d09e5f8715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_recipe_queue',
    sa.Column('swipe_session_id', sa.Integer(), nullable=False),
    sa.Column('queue', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['swipe_session_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('swipe_session_id')
    )
    op.add_column('swipe', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('swipe', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swipe', 'updated_at')
    op.drop_column('swipe', 'created_at')
    op.drop_table('session_recipe_queue')
    # ### end Alembic commands ###
