"""Loose ingredients not nullable

Revision ID: 187bd37a03d1
Revises: 0d5779030b9b
Create Date: 2023-03-13 15:12:38.496565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '187bd37a03d1'
down_revision = '0d5779030b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name.startswith('sqlite'):
        with op.batch_alter_table('recipe', schema=None) as batch_op:
            batch_op.alter_column('ingredients',
                existing_type=sa.JSON(),
                nullable=False)
        
    else: 
        op.alter_column('recipe', 'ingredients',
                existing_type=postgresql.JSON(astext_type=sa.Text()),
                nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'ingredients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
