"""add timestamps to sessions

Revision ID: 1d6b849f8442
Revises: 26f552937814
Create Date: 2023-04-04 11:20:41.055419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6b849f8442'
down_revision = '26f552937814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('swipe_session', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swipe_session', 'updated_at')
    op.drop_column('swipe_session', 'created_at')
    # ### end Alembic commands ###
