"""add file table

Revision ID: 233a9e5e93fe
Revises: adc3f1b55b2f
Create Date: 2023-04-04 10:47:24.893229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233a9e5e93fe'
down_revision = 'adc3f1b55b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
