"""add cascades

Revision ID: 26f552937814
Revises: 97a1035459f8
Create Date: 2023-04-04 10:57:50.099005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f552937814'
down_revision = '97a1035459f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name.startswith('sqlite'):
        with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
            batch_op.drop_constraint('recipe_ingredient_recipe_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key('recipe_ingredient_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('recipe_judgement', schema=None) as batch_op:
            batch_op.drop_constraint('recipe_judgement_recipe_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('recipe_judgement_user_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key('recipe_judgement_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('recipe_judgement_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
            
        with op.batch_alter_table('recipe_tag', schema=None) as batch_op:
            batch_op.drop_constraint('recipe_tag_tag_id_fkey', type_='foreignkey')
            batch_op.drop_constraint('recipe_tag_recipe_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key('recipe_tag_tag_id_fkey', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key('recipe_tag_recipe_id_fkey', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')


    else:
        op.drop_constraint('recipe_ingredient_recipe_id_fkey', 'recipe_ingredient', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_ingredient', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint('recipe_judgement_recipe_id_fkey', 'recipe_judgement', type_='foreignkey')
        op.drop_constraint('recipe_judgement_user_id_fkey', 'recipe_judgement', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_judgement', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'recipe_judgement', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint('recipe_tag_tag_id_fkey', 'recipe_tag', type_='foreignkey')
        op.drop_constraint('recipe_tag_recipe_id_fkey', 'recipe_tag', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_tag', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'recipe_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_tag', type_='foreignkey')
    op.drop_constraint(None, 'recipe_tag', type_='foreignkey')
    op.create_foreign_key('recipe_tag_recipe_id_fkey', 'recipe_tag', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('recipe_tag_tag_id_fkey', 'recipe_tag', 'tag', ['tag_id'], ['id'])
    op.drop_constraint(None, 'recipe_judgement', type_='foreignkey')
    op.drop_constraint(None, 'recipe_judgement', type_='foreignkey')
    op.create_foreign_key('recipe_judgement_user_id_fkey', 'recipe_judgement', 'user', ['user_id'], ['id'])
    op.create_foreign_key('recipe_judgement_recipe_id_fkey', 'recipe_judgement', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key('recipe_ingredient_recipe_id_fkey', 'recipe_ingredient', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
