"""cascade recipe tag

Revision ID: 344a58cf3e51
Revises: 4e1648340105
Create Date: 2023-05-10 13:11:53.060608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344a58cf3e51'
down_revision = '4e1648340105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
