"""add image to user

Revision ID: 3b0647ef8e61
Revises: 344a58cf3e51
Create Date: 2023-05-11 10:13:37.948034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0647ef8e61'
down_revision = '344a58cf3e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_filename_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'filename')
    # ### end Alembic commands ###
