"""server default ipv default voor timestamps

Revision ID: 3ce22000eb82
Revises: a969f51b4a08
Create Date: 2023-03-10 16:09:45.433896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce22000eb82'
down_revision = 'a969f51b4a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
