"""add groups

Revision ID: 470a8e0faa86
Revises: e1f6eee39261
Create Date: 2023-03-30 10:41:27.583747

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '470a8e0faa86'
down_revision = 'e1f6eee39261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), default=datetime.utcnow, nullable=False),
    sa.Column('updated_at', sa.DateTime(), default=datetime.utcnow, nullable=True),
    # Note that datetime.utcnow() is used instead of now() to get the current datetime in UTC timezone. This is recommended for consistency and compatibility across different databases.
    # (Was `server_default=sa.text('now()')` )
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_member')
    op.drop_table('group')
    # ### end Alembic commands ###
