"""add TimestampMixin back to user

Revision ID: 5d75f328ed6d
Revises: 509614271c4c
Create Date: 2023-03-10 09:50:39.627181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d75f328ed6d'
down_revision = '509614271c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user_profile', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_profile', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'updated_at')
    op.drop_column('user_profile', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
