"""user delete cascade

Revision ID: 7a97d4c9f2dd
Revises: e4d09e5f8715
Create Date: 2023-05-25 13:12:22.367594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a97d4c9f2dd'
down_revision = 'e4d09e5f8715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
