"""user-userprofile now one to one

Revision ID: 7f2b4a90519a
Revises: 5d75f328ed6d
Create Date: 2023-03-10 09:55:38.043892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2b4a90519a'
down_revision = '5d75f328ed6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
