"""add materials column

Revision ID: 80b62414d8f1
Revises: c9b910df48ee
Create Date: 2023-05-09 10:53:37.450964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b62414d8f1'
down_revision = 'c9b910df48ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('materials', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'materials')
    # ### end Alembic commands ###
