"""remove creator user from swipe_session

Revision ID: 855d38236fd8
Revises: 1318b666e8ea
Create Date: 2023-06-12 11:38:36.572010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d38236fd8'
down_revision = '1318b666e8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('swipe_session_user_id_fkey', 'swipe_session', type_='foreignkey')
    op.drop_column('swipe_session', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('swipe_session_user_id_fkey', 'swipe_session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
