"""SQLALECHMY 2.0 :o

Revision ID: 8681e6d2a9bd
Revises: 7049e1ffe5f6
Create Date: 2023-03-10 15:38:02.393632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8681e6d2a9bd'
down_revision = '7049e1ffe5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
