"""upgrade image to foreign key in recipe table

Revision ID: 97a1035459f8
Revises: 233a9e5e93fe
Create Date: 2023-04-04 10:49:56.813769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a1035459f8'
down_revision = '233a9e5e93fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipe', 'file', ['image'], ['filename'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    # ### end Alembic commands ###
