"""recipe has ingredients

Revision ID: 992096cefe0a
Revises: 187bd37a03d1
Create Date: 2023-03-23 14:50:15.072368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '992096cefe0a'
down_revision = '187bd37a03d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
