"""Update user

Revision ID: 9f57033ee4c1
Revises: d90ee3b5a508
Create Date: 2023-03-09 13:38:27.175138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f57033ee4c1'
down_revision = 'd90ee3b5a508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name.startswith('sqlite'):
        with op.batch_alter_table("user_profile") as batch_op:
            batch_op.create_foreign_key('user_profile_user_id_fkey', 'user', ['user_id'], ['id'])

    else:
        op.drop_constraint('user_profile_user_id_fkey', 'user_profile', type_='foreignkey')
        op.create_foreign_key(None, 'user_profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.create_foreign_key('user_profile_user_id_fkey', 'user_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
