"""pk gefixt van tabel

Revision ID: a969f51b4a08
Revises: 8681e6d2a9bd
Create Date: 2023-03-10 15:39:26.146281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a969f51b4a08'
down_revision = '8681e6d2a9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredient_ingredient_id_fkey', 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredient', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key('recipe_ingredient_ingredient_id_fkey', 'recipe_ingredient', 'recipe', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
