"""Group id on session

Revision ID: adc3f1b55b2f
Revises: 470a8e0faa86
Create Date: 2023-04-04 10:11:04.780314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc3f1b55b2f'
down_revision = '470a8e0faa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name.startswith('sqlite'):
        with op.batch_alter_table('swipe_session') as batch_op:
            batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('swipe_session_group_id', 'group', ['group_id'], ['id'])

    else:
        op.add_column('swipe_session', sa.Column('group_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'swipe_session', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swipe_session', type_='foreignkey')
    op.drop_column('swipe_session', 'group_id')
    # ### end Alembic commands ###
