"""REVISION NAME

Revision ID: b0d46d5520f2
Revises: a16891dc5b56
Create Date: 2023-04-21 17:38:28.834993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0d46d5520f2"
down_revision = "a16891dc5b56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
