"""updated at timestamp kan null zijn

Revision ID: be0302e52bc3
Revises: 3ce22000eb82
Create Date: 2023-03-10 16:11:38.547935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be0302e52bc3'
down_revision = '3ce22000eb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name.startswith('sqlite'):
        with op.batch_alter_table('recipe', schema=None) as batch_op:
            batch_op.alter_column('updated_at',
                existing_type=sa.TIMESTAMP(),
                nullable=True)
            
        with op.batch_alter_table('recipe_judgement', schema=None) as batch_op:
            batch_op.alter_column('updated_at',
                existing_type=sa.TIMESTAMP(),
                nullable=True)
            
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('updated_at',
                existing_type=sa.TIMESTAMP(),
                nullable=True)
            
        with op.batch_alter_table('user_profile', schema=None) as batch_op:
            batch_op.alter_column('updated_at',
                existing_type=sa.TIMESTAMP(),
                nullable=True)
        
    else: 
        op.alter_column('recipe', 'updated_at',
                existing_type=postgresql.TIMESTAMP(),
                nullable=True)
        op.alter_column('recipe_judgement', 'updated_at',
                existing_type=postgresql.TIMESTAMP(),
                nullable=True)
        op.alter_column('user', 'updated_at',
                existing_type=postgresql.TIMESTAMP(),
                nullable=True)
        op.alter_column('user_profile', 'updated_at',
                existing_type=postgresql.TIMESTAMP(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('recipe_judgement', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('recipe', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
