"""preparing_time -> preparation_time

Revision ID: c9b910df48ee
Revises: a16891dc5b56
Create Date: 2023-05-09 09:53:35.618883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b910df48ee'
down_revision = 'a16891dc5b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('preparation_time', sa.Integer(), nullable=True))
    # copy data from preparing_time to preparation_time
    op.execute("UPDATE recipe SET preparation_time = preparing_time")
    op.drop_column('recipe', 'preparing_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('preparing_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # copy data from preparation_time to preparing_time
    op.execute("UPDATE recipe SET preparing_time = preparation_time")
    op.drop_column('recipe', 'preparation_time')
    # ### end Alembic commands ###
