"""Update user 2

Revision ID: ca0d560c12da
Revises: 9f57033ee4c1
Create Date: 2023-03-09 13:41:20.533667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0d560c12da'
down_revision = '9f57033ee4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
