"""swipe_match as object p2

Revision ID: cdeb93973cf1
Revises: fc8bf530aeef
Create Date: 2023-06-12 15:39:39.787612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdeb93973cf1'
down_revision = 'fc8bf530aeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
