"""unit is gone, only in ingredientstable

Revision ID: e1f6eee39261
Revises: 992096cefe0a
Create Date: 2023-03-23 15:03:02.701822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f6eee39261'
down_revision = '992096cefe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name.startswith('sqlite'):
        with op.batch_alter_table('recipe_ingredient') as batch_op:
            batch_op.drop_constraint('recipe_ingredient_unit_id_fkey', type_='foreignkey')
            batch_op.drop_column('unit_id')
            batch_op.add_column(sa.Column('unit', sa.String(), nullable=False))

        op.drop_table('unit')

    else:
        op.drop_constraint('recipe_ingredient_unit_id_fkey', 'recipe_ingredient', type_='foreignkey')
        op.drop_column('recipe_ingredient', 'unit_id')
        op.drop_table('unit')
        op.add_column('recipe_ingredient', sa.Column('unit', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredient', sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('recipe_ingredient_unit_id_fkey', 'recipe_ingredient', 'unit', ['unit_id'], ['id'])
    op.drop_column('recipe_ingredient', 'unit')
    op.create_table('unit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='unit_pkey')
    )
    # ### end Alembic commands ###
