"""spiciness

Revision ID: e4d09e5f8715
Revises: d24375ec75fa
Create Date: 2023-05-25 10:54:11.990765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d09e5f8715'
down_revision = 'd24375ec75fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('spiciness', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('recipe', 'spiciness', server_default=None, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'spiciness')
    # ### end Alembic commands ###
