"""swipe_match p3

Revision ID: ebe4a1c77841
Revises: cdeb93973cf1
Create Date: 2023-06-12 15:40:38.764241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe4a1c77841'
down_revision = 'cdeb93973cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('match_recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'swipe_session', 'recipe', ['match_recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swipe_session', type_='foreignkey')
    op.drop_column('swipe_session', 'match_recipe_id')
    # ### end Alembic commands ###
