"""adit image_foreing key column name

Revision ID: ec9f0f0081a5
Revises: 26f552937814
Create Date: 2023-04-04 16:41:07.392920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9f0f0081a5'
down_revision = '26f552937814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('filename', sa.String(), nullable=False))
    op.drop_constraint('recipe_image_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'file', ['filename'], ['filename'], ondelete='CASCADE')
    op.drop_column('recipe', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_image_fkey', 'recipe', 'file', ['image'], ['filename'], ondelete='CASCADE')
    op.drop_column('recipe', 'filename')
    # ### end Alembic commands ###
