"""swipe session_match to swipe_match

Revision ID: fa40ea245fec
Revises: 00b898f6b7ea
Create Date: 2023-06-12 15:15:12.394847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa40ea245fec'
down_revision = '00b898f6b7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('swipe_match', sa.Integer(), nullable=True))
    op.drop_constraint('swipe_session_session_match_fkey', 'swipe_session', type_='foreignkey')
    op.create_foreign_key(None, 'swipe_session', 'recipe', ['swipe_match'], ['id'])
    op.drop_column('swipe_session', 'session_match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('session_match', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'swipe_session', type_='foreignkey')
    op.create_foreign_key('swipe_session_session_match_fkey', 'swipe_session', 'recipe', ['session_match'], ['id'])
    op.drop_column('swipe_session', 'swipe_match')
    # ### end Alembic commands ###
