"""swipe_match as object?

Revision ID: fc8bf530aeef
Revises: fa40ea245fec
Create Date: 2023-06-12 15:17:46.985545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8bf530aeef'
down_revision = 'fa40ea245fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('swipe_session_swipe_match_fkey', 'swipe_session', type_='foreignkey')
    op.drop_column('swipe_session', 'swipe_match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swipe_session', sa.Column('swipe_match', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('swipe_session_swipe_match_fkey', 'swipe_session', 'recipe', ['swipe_match'], ['id'])
    # ### end Alembic commands ###
