# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Functional and quality tests for Python

env: 
  DU: ${{ secrets.DU }}
  DP: ${{secrets.DP}}
  DB: ${{secrets.DB}}
  H: ${{secrets.H}}
  P: ${{secrets.P}}
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
  HASH_MIN_LEN: ${{secrets.HASH_MIN_LEN}}
  HASH_SALT: ${{secrets.HASH_SALT}}
  AZURE_BLOB_ACCOUNT_URL: ${{secrets.AZURE_BLOB_ACCOUNT_URL}}
  IMAGE_CONTAINER_NAME: ${{secrets.IMAGE_CONTAINER_NAME}}
  AZURE_BLOB_CONNECTION_STRING: ${{secrets.AZURE_BLOB_CONNECTION_STRING}}
  AZURE_IMAGE_URL_BASE: ${{secrets.AZURE_IMAGE_URL_BASE}}
  PRIVATE_KEY_PASSWORD: ${{secrets.PRIVATE_KEY_PASSWORD}}
  
  
on:
  push:
    branches: [ "alpha" ]
  pull_request:
    branches: [ "alpha" ]

permissions:
  contents: read

jobs:
  build:
    name: quality code test

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements_ubuntu.txt
    #- name: Lint with flake8
    #  run: |
        # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
     #   flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        coverage run -m pytest 
        coverage xml

    - name: Get Cover 
      uses: orgoro/coverage@v3
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdNew: 0.85
          thresholdModified: 0.85
